"""add execution queue

Revision ID: b44aa6abc0cf
Revises: 83053b452755
Create Date: 2026-08-13 09:57:24.141417

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b44aa6abc0cf"
down_revision: Union[str, Sequence[str], None] = "83053b452755"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_queue",
        sa.Column("task_execution_id", sa.UUID(), nullable=False),
        sa.Column("claim_token", sa.UUID(), nullable=True),
        sa.Column("claimed_by", sa.UUID(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("task_execution_id"),
    )
    op.create_index(
        op.f("ix_execution_queue_claimed_by"), "execution_queue", ["claimed_by"], unique=False
    )
    op.create_index(
        op.f("ix_execution_queue_last_heartbeat"),
        "execution_queue",
        ["last_heartbeat"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_queue_queued_at"), "execution_queue", ["queued_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_execution_queue_queued_at"), table_name="execution_queue")
    op.drop_index(op.f("ix_execution_queue_last_heartbeat"), table_name="execution_queue")
    op.drop_index(op.f("ix_execution_queue_claimed_by"), table_name="execution_queue")
    op.drop_table("execution_queue")
    # ### end Alembic commands ###
